# Generated by Django 4.2.2 on 2023-07-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=255)),
                ('trailer', models.URLField()),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Animation', 'Animation'), ('Animation', 'Animation'), ('Thriller', 'Thriller'), ('Mistery', 'Mistery')])),
            ],
        ),
    ]
