# Generated by Django 4.2.2 on 2023-07-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='image',
            field=models.URLField(),
        ),
    ]
