# Generated by Django 4.2.2 on 2023-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0002_alter_moviemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='image',
            field=models.URLField(max_length=800),
        ),
    ]
