# Generated by Django 4.2.2 on 2023-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0003_alter_moviemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Animation', 'Animation'), ('Animation', 'Animation'), ('Thriller', 'Thriller'), ('Mistery', 'Mistery')], max_length=100),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
