# Generated by Django 4.2.2 on 2023-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0004_alter_moviemodel_genre_alter_moviemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='description',
            field=models.TextField(max_length=805),
        ),
    ]
