# Generated by Django 4.2.2 on 2023-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0008_alter_moviemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
