# Generated by Django 4.2.2 on 2023-07-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0009_alter_moviemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
