# Generated by Django 4.2.2 on 2023-07-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0010_alter_moviemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
