# Generated by Django 4.2.2 on 2023-07-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0011_moviemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
