# Generated by Django 4.2.2 on 2023-08-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0016_alter_rating_unique_together_rating_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
