# Generated by Django 4.2.2 on 2023-08-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0018_userwatchlist_movielikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielikes',
            name='disliked',
            field=models.BooleanField(default=False),
        ),
    ]
