# Generated by Django 4.2.2 on 2023-08-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_auth', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
