# Generated by Django 4.2.2 on 2023-08-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_auth', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/images/no-profile.JPEG', upload_to='static/images/profile/'),
        ),
    ]
